python1/py1/django/mysite/account/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = "account"

urlpatterns = [
    #path('login/', views.user_login, name='user_login'),
    path('login/',auth_views.LoginView.as_view(template_name='account/login.html'),name="user_login"),
    path('loginout/',auth_views.LogoutView.as_view(template_name='account/loginout.html'),name="user_loginout"),
    path('register/',views.register,name="user_register"),
    path('password-change/',auth_views.PasswordChangeView.as_view(template_name='account/password_change_form.html' ,success_url="/account/password-change-done/"), name="password_change"),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html", email_template_name="account/password_reset_email.html",subject_template_name="account/password_reset_subject.txt", success_url='/account/password-reset-done/'), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html", success_url='/account/password-reset-complete/'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('my-information/',views.myself,name="my-information"),
    path('edit-my-information/',views.myself_edit,name="edit_my_information"),
    path('my-image/',views.my_image,name="my_image"),
]

python1/py1/django/mysite/blog/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/',views.blog_article,name="blog_article")
]

python1/py1/django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace='account')),
]

python1/py1/django/mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta  name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>      
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">    
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}    
        {% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
</body>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>    
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>    
</html>

python1/py1/django/mysite/templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.itdifer.com</p>
<div>

python1/py1/django/mysite/templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com">
                <img src="{% static '/images/logo.png' %}" width="100px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navgation">
                <li><a href="{% url 'blog:blog_title'%}">BLOG</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
            {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">
                        {{ user.username }}<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:my-information' %}">个人信息</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'account:user_loginout' %}">LOGIN OUT</a></li>
            {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
            {% endif %}
            </ul>
        </div>
    </nav>
</div>